module.exports = {
    NULL_VALUE: "필요한 값이 없습니다",
    OUT_OF_VALUE: "파라미터 값이 잘못되었습니다",
    EXIST_ID: "이미 존재하는 아이디입니다.",
    LOGIN_FAIL:"로그인 실패",
    LOGIN_SUCCESS:"로그인 성공",
    SIGNUP_FAIL: "회원 가입 실패",
    SIGNUP_SUCCESS:"회원 가입 성공",
    READ_SUCCESS: "읽기 성공",
    READ_FAIL: "읽기 실패",
    SAVE_SUCCESS: "저장 성공",
    SAVE_FAIL: "저장 실패",
    DELETE_SUCCESS: "삭제 성공",
    DELETE_FAIL: "삭제 실패",


    CREATE_TOKEN: "토큰 발급 완료.",
    REFRESH_TOKEN: "토큰 재발급 완료.",
    INVALID_TOKEN: "잘못된 형식의 토큰입니다.",
    EMPTY_TOKEN: "토큰값이 존재하지 않습니다.",
    EXPRIED_TOKEN: "만료된 토큰입니다.",
    EMPTY_REFRESH_TOKEN: "재발급 토큰이 존재하지 않습니다.",
    CREATE_TOKEN: "토큰 발급 완료.",
    REFRESH_TOKEN: "토큰 재발급 완료.",


    BANNER_SUCCESS : "배너 조회 성공",
    NO_SELECT_AUTHORITY: "조회 권한 없음.",
    USER_SELECTED: "회원 조회 성공.",
    MAIN_SUCCESS:"메인 웹툰 보기 성공",
    EPISODE_SAVE_FAIL:"에피소드 등록 실패",
    EPISODE_SAVE_SUCCESS:"에피소드 등록 성공",
    GET_EPISODE_FAIL:"에피소드 읽기 실패",
    GET_EPISODE_SUCCESS:"에피소드 읽기 성공",
    EPISODE_EMPTY:"에피소드가 존재하지 않습니다",
    EPISODE_DB_ERROR:"에피소드 DB 에러",
    GET_COMMNETS_FAIL:"댓글 읽기 실패",
    GET_COMMNETS_SUCCESS:"댓글 읽기 성공",
    COMMENTS_DB_ERROR:"댓글 DB 에러",

    POST_COMMNETS_FAIL:"댓글 등록 실패",
    POST_COMMNETS_SUCCESS:"댓글 등록 성공",
    USER_NOT_EXIST:"존재하지 않는 유저입니다.",
    COMMENTS_NOT_EXISTS:"존재하지 않는 댓글입니다.",
    COMMENTS_EMPTY:"댓글내용이 없습니다.",
    EXIST_WEBTOON:"이미 존재하는 웹툰입니다.",
    COMMENTS_EXISTS:"이미 존재하는 댓글입니다."
};